"""Pass 2 prompt templates.

Templates for global synthesis sent to the reasoning model.
"""

PASS2_SYSTEM_PROMPT = (
    "You are an AI assistant synthesizing analysis results from multiple "
    "video segments into a coherent full-video report. "
    "You will receive segment summaries, key moments, and tags from all chunks. "
    "Return your synthesis as structured JSON with the fields described below. "
    "Be thorough in connecting themes across segments. "
    "Create meaningful chapter titles that reflect the actual content.\n\n"
    "CRITICAL — connect information across segments, do not just summarize each "
    "segment in isolation:\n"
    "- RESOLVE CHARACTER/ENTITY IDENTITIES: the same person is often referred to "
    "by different names, titles, or roles across segments (e.g. a first name in "
    "one segment and a title/surname in another, or a role like 'the new hire' "
    "vs a name). Detect when references point to the SAME individual and unify "
    "them, recording every alias. Watch for name spellings that drift slightly "
    "between segments (transcription variance) and treat close variants as the "
    "same entity.\n"
    "- TRACK THE PLOT/CAUSAL CHAIN: identify who did what to whom, and the "
    "consequences — especially antagonists, victims, and pivotal actions "
    "(e.g. who harmed or deceived whom). State these explicitly rather than "
    "leaving them implied across scattered segments.\n"
    "- The executive and detailed summaries MUST reflect these resolved "
    "identities and key causal events, not a scene-by-scene recap."
)

PASS2_USER_PROMPT_TEMPLATE = (
    "FULL VIDEO SYNTHESIS\n"
    "Total segments analyzed: {num_chunks}\n"
    "Video duration: {video_duration}s\n\n"
    "--- SEGMENT SUMMARIES ---\n"
    "{chunk_summaries}\n\n"
    "--- ALL KEY MOMENTS ---\n"
    "{all_key_moments}\n\n"
    "--- ALL TAGS ---\n"
    "{all_tags}\n\n"
    "--- PIVOTAL QUOTES (flagged by segment analysis) ---\n"
    "{pivotal_quotes}\n\n"
    "--- CHARACTERS & CAUSAL EVENTS (structured, from segment analysis) ---\n"
    "{events_digest}\n\n"
    "--- FULL TRANSCRIPT (verbatim dialogue) ---\n"
    "{transcript}\n\n"
    "The segment summaries above are lossy. The transcript is the ground truth "
    "for what is SAID — use it to establish plot and causality (who kills whom, "
    "confessions, identity reveals) that the summaries gloss over. When speaker "
    "labels are present, attribute lines to the correct speaker; when absent, "
    "infer the speaker from context and note uncertainty rather than guessing.\n\n"
    "--- TASK ---\n"
    "Return a JSON object with these fields:\n"
    "- executive_summary: 1 paragraph overview\n"
    "- detailed_summary: 3-5 paragraphs by theme\n"
    "- chapters: array of {{start_seconds, end_seconds, title, summary}}\n"
    "    (start_seconds/end_seconds are integer SECONDS from the video start, in\n"
    "    the range 0..{video_duration}; do NOT use minutes or chunk indices)\n"
    "- key_moments: array of {{time, title, description, importance(1-5)}}\n"
    "    (time is SECONDS from the video start, 0..{video_duration})\n"
    "- characters: array of {{name, aliases, description}} — every distinct "
    "person/entity, with ALL other names/titles/roles they are referred to by in "
    "aliases (unify the same individual across segments), and a one-line "
    "description of their role in the video\n"
    "- key_events: array of {{time, description, participants}} — the pivotal "
    "plot/causal events (who did what to whom and the consequence), time in "
    "SECONDS (0..{video_duration}), participants as a list of character names\n"
    "- speaker_summary: object mapping speaker to topics discussed\n"
    "- visual_summary: how visuals progress through the video\n"
    "- audio_summary: audio events and patterns\n"
    "- action_items: array of things viewer should do/learn\n"
    "- tags: comprehensive keyword list\n\n"
    "All timestamps are in SECONDS (0..{video_duration}), never minutes. "
    "Chapters should cover the full video with no gaps; the last chapter's "
    "end_seconds should be close to {video_duration}."
)
