"""Pass 1 prompt templates.

Templates for segment-level analysis sent to the reasoning model.
"""

PASS1_SYSTEM_PROMPT = (
    "You are an AI assistant analyzing segments of a video. "
    "For each segment, you will receive the transcript, visual descriptions, "
    "OCR text (if any), audio events, and scene data. "
    "Return your analysis as structured JSON with the fields described below. "
    "Be precise with timestamps. Do not make up timestamps or content that "
    "is not present in the input data.\n\n"
    "PRESERVE PLOT-BEARING DETAIL. A later stage synthesizes all segments into a "
    "whole-video narrative and relies on you not to summarize away the facts that "
    "carry the story. In particular: keep proper NAMES exactly as spoken; capture "
    "pivotal dialogue VERBATIM in the quotes field (accusations, confessions, "
    "reveals of identity or relationship, threats, admissions of who did what to "
    "whom); and in the summary state causal facts explicitly (who harmed/killed/"
    "deceived whom) rather than vaguely ('a character is accused'). Do not "
    "sanitize a killing or a betrayal into a euphemism."
)

PASS1_USER_PROMPT_TEMPLATE = (
    "SEGMENT ANALYSIS\n"
    "Video duration: {video_duration} | Segment: {segment_time}\n\n"
    "TRANSCRIPT:\n{transcript}\n\n"
    "VISUAL DESCRIPTIONS:\n{visual_captions}\n\n"
    "OCR TEXT:\n{ocr_text}\n\n"
    "AUDIO EVENTS:\n{audio_events}\n\n"
    "SCENES:\n{scenes}\n\n"
    "---\n"
    "Return a JSON object with these fields:\n"
    "- summary: 2-3 sentence summary of what happens; name people explicitly and "
    "state causal facts (who did what to whom) when the dialogue reveals them\n"
    "- characters_present: array of the distinct people/entities appearing or "
    "speaking in this segment, named as specifically as the input allows (use "
    "the name if spoken, else a role/description like 'the woman in the tank top' "
    "or a speaker label)\n"
    "- events: array of {{actor, action, target}} — the causal actions in this "
    "segment (e.g. {{\"actor\":\"Linda\",\"action\":\"accuses of murder\","
    "\"target\":\"Bradley\"}}); include harm/killing/betrayal/deception. Leave "
    "actor/target as best-known label if unnamed. Omit if nothing causal happens\n"
    "- key_moments: array of {{time, description}}\n"
    "- tags: array of topic/action tags\n"
    "- quotes: array of {{time, speaker, text}} — include EVERY pivotal line "
    "verbatim: accusations, confessions, identity/relationship reveals, threats, "
    "and any admission of harm or killing. Prefer quoting too much over losing a "
    "plot point\n"
    "- issues: array of error/warning/problem strings\n"
    "- detected_actions: array of action strings\n"
    "- speaker_labels: array of speaker labels found\n\n"
    "Use timestamps in seconds relative to the video start."
)
